# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            code 'n hike
tagline:          'leave no log trace'
description:      'when a software developer meet the hiking trails'
url:              http://markhughneri.com
baseurl:          /

author:
  name:           'Mark Hugh Neri'
  url:            https://twitter.com/markhughneri

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kimerran/

gems:             [jekyll-paginate, jekyll-gist]
paginate_path:    "page:num"
